- name: Install build essentials for ubuntu
  apt:
    name: build-essential
    state: present

- name: Install gedit text editor
  apt:
    name: gedit
    state: present

- name: Intall file-roller archive manager
  apt:
    name: file-roller
    state: present

- name: Install plank for app dock
  apt:
    name: plank
    state: present

- name: Install bash completion
  apt:
    name: bash-completion
    state: present

- name: Check Gyazo installed
  shell: which gyazo
  register: gyazo_check
  ignore_errors: True

# instructions taken from gyazo for linux
# https://github.com/gyazo/Gyazo-for-Linux
- name: Install Gyazo
  shell: |
    curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
    apt-get install gyazo -y
  when: gyazo_check.rc == 1
