- name: Install build essentials for ubuntu
  apt:
    name: build-essential
    state: present

- name: Install gedit text editor
  apt:
    name: gedit
    state: present

- name: Intall file-roller archive manager
  apt:
    name: file-roller
    state: present

- name: Install bash completion
  apt:
    name: bash-completion
    state: present

- name: Check Gyazo installed
  shell: which gyazo
  register: gyazo_check
  ignore_errors: True

# instructions taken from gyazo for linux
# https://github.com/gyazo/Gyazo-for-Linux
- name: Install Gyazo
  shell: |
    curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo bash
    apt-get install gyazo -y
  when: gyazo_check.rc == 1

- name: Install i3
  apt:
    name: i3
    state: present

- name: Install i3blocks
  apt:
    name: i3blocks
    state: present

- name: Install nitogren
  apt:
    name: nitrogen
    state: present
    
- name: Install tmux
  apt:
    name: tmux
    state: present

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Disable chsh authentication
  lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: 'auth sufficient  pam_shells.so'

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: False

- name: Re-enable chsh authentication
  lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: 'auth required  pam_shells.so'

 name: Clone dotfiles
  git:
    repo: https://github.com/neetjn/dotfiles.git
    dest: /tmp/dotfiles
    version: master

- name: Copy dotfiles
  shell: |
    chown -R "{{host_username}}" /tmp/dotfiles/
    cp -r /tmp/dotfiles/* "{{home_directory}}"
    cp -r /tmp/dotfiles/.* "{{home_directory}}"
    rm -rf "{{home_directory}}/.git"
  ignore_errors: yes

- name: Install jq
  apt:
    name: jq
  state: present

- name: Install snapd
  apt:
    name: snapd
    state: present
